version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: nyu
    volumes:
      - ..:/app
      - ~/.bluemix/:/home/devops/.bluemix/
    command: sleep infinity
    environment:
      FLASK_APP: service:app
      COUCHDB_HOST: couchdb
      COUCHDB_PORT: 5984
      COUCHDB_USER: ${COUCHDB_USER:-admin}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:-pass}
    networks:
      - dev
    depends_on:
      - couchdb

  # CouchDB Dashboard: http://127.0.0.1:5984/_utils"
  couchdb:
    image: couchdb:latest
    hostname: couchdb
    ports:
      - 5984:5984
    volumes:
      - couchdb:/opt/couchdb/data
    environment:
      COUCHDB_USER: ${COUCHDB_USER:-admin}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:-pass}
    networks:
      - dev

volumes:
  couchdb:

networks:
  dev:
